version: 2
shared: &shared
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx1g
    TERM: dumb
    GOVERSION: 17.4.0
  steps:
    - checkout

    - restore_cache:
        key: maven-{{ checksum "pom.xml" }}

    - run:
        name: Maven Get Dependencies
        command: mvn dependency:go-offline --fail-never

    - save_cache:
        paths:
          - ~/.m2
        key: maven-{{ checksum "pom.xml" }}

    - run:
        name: Maven Build and test
        command: mvn -Dgo.version=${GOVERSION} clean package

    - persist_to_workspace:
        root: ./target
        paths:
          - go-maven-poller-plugin.jar

    - store_artifacts:
        path: ./target/go-maven-poller-plugin.jar

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-buster
    <<: *shared
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    <<: *shared
  jdk13:
    docker:
      - image: circleci/openjdk:13-jdk-buster
    <<: *shared
  jdk14:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    <<: *shared
  jdk15:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    <<: *shared
  gocd_api_20_10_0:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb
      GOVERSION: 20.10.0
    <<: *shared
  coverage:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run:
          name: Maven Get Dependencies
          command: mvn dependency:go-offline --fail-never
      - run:
          name: Maven Build and test
          command: mvn clean test jacoco:report
      - run:
          name: Codacy Coverage upload
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh)

  upload_jfrog:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb
    steps:
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run:
          name: Upload latest to JFrog BinTray
          command: curl -T /tmp/workspace/go-maven-poller-plugin.jar -u${JFROG_USER}:${JFROG_APIKEY} https://api.bintray.com/content/sfuhrm/go-maven-poller/plugin/latest/go-maven-poller-plugin.jar

workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
      - jdk13
      - jdk14
      - jdk15
      - coverage
      - gocd_api_20_10_0
      - upload_jfrog:
          requires:
            - jdk8
