# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration Test

env:
 GOVERSION: v19.1.0
 ACCEPT: application/vnd.go.cd.v4+json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Start a docker container
      run: |
        mkdir -p /tmp/workspace/external
        cp target/go-maven-poller-plugin.jar /tmp/workspace/external
        docker run --name gocd-server \
         -v /tmp/workspace/external:/godata/plugins/external \
         -d -p8153:8153 \
         gocd/gocd-server:${GOVERSION}
    - name: Wait and get the plugin info via API
      run: |
        echo "Accept: ${ACCEPT} for GoCD version ${GOVERSION}"
        for (( i = 0; i < 180 ; i++ )); do
          # busy loop sleep
          sleep 1
          echo -n "."
          # download API
          curl > plugin_info.json --silent \
          -H "Accept: ${ACCEPT}" \
          http://localhost:8153/go/api/admin/plugin_info/maven-repo \
          || continue
          # break if success
          grep ARTIFACT_ID plugin_info.json && break
        done
    - uses: actions/upload-artifact@v2
      with:
        name: output-json
        path: plugin_info.json
    - name: Kill the docker container
      run: |
        docker container kill gocd-server
