# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integration Test

env:
 GOVERSION: v19.1.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Start a docker container
      run: |
        mkdir -p /tmp/workspace/external
        cp target/go-maven-poller-plugin.jar /tmp/workspace/external
        docker run --name gocd-server \
         -v /tmp/workspace/external:/godata/plugins/external \
         -d -p8153:8153 \
         gocd/gocd-server:${GOVERSION}
